/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kinderatelier.view;
import com.mycompany.kinderatelier.programa.KinderAtelier;
import com.mycompany.kinderatelier.programa.Estudiante;
import com.mycompany.kinderatelier.programa.Profesor;
import com.mycompany.kinderatelier.programa.Matricula;
import com.mycompany.kinderatelier.lectura.Lector;

/**
 *
 * @author Ángela
 */
public class VentanaReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReportes.class.getName());

    /**
     * Creates new form VentanaReportes
     */
    private KinderAtelier kinder;
    public VentanaReportes(KinderAtelier dKinder) {
        initComponents();
        kinder = dKinder;
    }
    private String elegirDeLista(String[] opciones, String mensaje) {
        String lista;
        int eleccion;
 
        lista = mensaje + "\n\n";
        for (int i = 0; i < opciones.length; i++) {
            lista = lista + (i + 1) + ". " + opciones[i] + "\n";
        }
        eleccion = Lector.leerEntero(lista);
        while (eleccion < 1 || eleccion > opciones.length) {
            Lector.mostrar("Opcion invalida.");
            eleccion = Lector.leerEntero(lista);
        }
        return opciones[eleccion - 1];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ocupacionTalleres = new javax.swing.JButton();
        ocupacionPorTaller = new javax.swing.JButton();
        catalogoActividades = new javax.swing.JButton();
        talentosPorCategoria = new javax.swing.JButton();
        distribucionTalentos = new javax.swing.JButton();
        top10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jLabel1.setText("REPORTES");

        ocupacionTalleres.setText("Ocupacion de talleres");
        ocupacionTalleres.addActionListener(this::ocupacionTalleresActionPerformed);

        ocupacionPorTaller.setText("Estudiantes por taller");
        ocupacionPorTaller.addActionListener(this::ocupacionPorTallerActionPerformed);

        catalogoActividades.setText("Catálogo de actividades");
        catalogoActividades.addActionListener(this::catalogoActividadesActionPerformed);

        talentosPorCategoria.setText("Talentos por categoria");
        talentosPorCategoria.addActionListener(this::talentosPorCategoriaActionPerformed);

        distribucionTalentos.setText("Distribución de talentos");
        distribucionTalentos.addActionListener(this::distribucionTalentosActionPerformed);

        top10.setText("Top 10 estudiantes");
        top10.addActionListener(this::top10ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ocupacionTalleres)
                    .addComponent(catalogoActividades)
                    .addComponent(distribucionTalentos))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(talentosPorCategoria)
                    .addComponent(ocupacionPorTaller)
                    .addComponent(top10))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ocupacionTalleres)
                    .addComponent(ocupacionPorTaller))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catalogoActividades)
                    .addComponent(talentosPorCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distribucionTalentos)
                    .addComponent(top10))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocupacionTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocupacionTalleresActionPerformed
        Lector.mostrar(kinder.mostrarOcupacion());
    }//GEN-LAST:event_ocupacionTalleresActionPerformed

    private void ocupacionPorTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocupacionPorTallerActionPerformed
        String taller = elegirDeLista(KinderAtelier.RAMAS, "de cual taller quiere ver la lista?");
        Lector.mostrar(kinder.listarPorRama(taller));
    }//GEN-LAST:event_ocupacionPorTallerActionPerformed

    private void catalogoActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoActividadesActionPerformed
        Lector.mostrar(kinder.listarTodasLasRamas());
    }//GEN-LAST:event_catalogoActividadesActionPerformed

    private void talentosPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talentosPorCategoriaActionPerformed
        String talento = elegirDeLista(KinderAtelier.TALENTOS, "Cual categoria de talento?");
        Lector.mostrar(kinder.listarPorTalento(talento));
    }//GEN-LAST:event_talentosPorCategoriaActionPerformed

    private void distribucionTalentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribucionTalentosActionPerformed
       Lector.mostrar(kinder.mostrarDistribucionTalentos());
    }//GEN-LAST:event_distribucionTalentosActionPerformed

    private void top10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top10ActionPerformed
        Lector.mostrar(kinder.generarMejores10Texto());
    }//GEN-LAST:event_top10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catalogoActividades;
    private javax.swing.JButton distribucionTalentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ocupacionPorTaller;
    private javax.swing.JButton ocupacionTalleres;
    private javax.swing.JButton talentosPorCategoria;
    private javax.swing.JButton top10;
    // End of variables declaration//GEN-END:variables
}
