/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kinderatelier.view;
import com.mycompany.kinderatelier.programa.KinderAtelier;
import com.mycompany.kinderatelier.lectura.Lector;
/**
 *
 * @author Ángela
 */
public class VentanaAspirantes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAspirantes.class.getName());
    private KinderAtelier kinder;
    /**
     * Creates new form VentanaAspirantes
     */
    public VentanaAspirantes(KinderAtelier dKinder) {
        initComponents();
        kinder = dKinder;
        kinder.setCantidadAspirantes(Lector.cargarCsv(kinder.getAspirantes(), kinder.getCantidadAspirantes()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarAspiranteBtn = new javax.swing.JButton();
        guardarAspirantesCsvBtn = new javax.swing.JButton();
        generarTablaAspirantesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrarAspiranteBtn.setText("Registrar aspirante");
        registrarAspiranteBtn.addActionListener(this::registrarAspiranteBtnActionPerformed);

        guardarAspirantesCsvBtn.setText("Guardar aspirantes (CSV)");
        guardarAspirantesCsvBtn.addActionListener(this::guardarAspirantesCsvBtnActionPerformed);

        generarTablaAspirantesBtn.setText("Generar PDF aspirantes");
        generarTablaAspirantesBtn.addActionListener(this::generarTablaAspirantesBtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jLabel1.setText("ASPIRANTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(guardarAspirantesCsvBtn)
                .addGap(18, 18, 18)
                .addComponent(generarTablaAspirantesBtn)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(registrarAspiranteBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registrarAspiranteBtn)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarTablaAspirantesBtn)
                    .addComponent(guardarAspirantesCsvBtn))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarAspiranteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAspiranteBtnActionPerformed
        kinder.registrarAspirante();
    }//GEN-LAST:event_registrarAspiranteBtnActionPerformed

    private void guardarAspirantesCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAspirantesCsvBtnActionPerformed
        Lector.guardarCsv(kinder.getAspirantes(), kinder.getCantidadAspirantes());
    }//GEN-LAST:event_guardarAspirantesCsvBtnActionPerformed

    private void generarTablaAspirantesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarTablaAspirantesBtnActionPerformed
        kinder.crearTabla();
        try {
            String archivo = "reporte_aspirantes.pdf";
            String os = System.getProperty("os.name").toLowerCase();

            if (os.contains("win")) {
                Runtime.getRuntime().exec("cmd /c start " + archivo);
            } else if (os.contains("nix") || os.contains("nux")) {
                Runtime.getRuntime().exec("xdg-open " + archivo);
            } else if (os.contains("mac")) {
                Runtime.getRuntime().exec("open " + archivo);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo abrir el PDF de aspirantes", e);
        }
    }//GEN-LAST:event_generarTablaAspirantesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarTablaAspirantesBtn;
    private javax.swing.JButton guardarAspirantesCsvBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registrarAspiranteBtn;
    // End of variables declaration//GEN-END:variables
}
